### ISSUE TITLE
(User Story - Admin) - Admin Access Pages

### ISSUE THREAD

**Issue by suha-ab** [LachezaraLaz/341-soen341project2023#21]
As an admin, I would like to be able to view the database of accounts to create, edit, delete, and manage accounts.

**Comment by suha-ab** [comment]
Story Points: 8

**Comment by m-coscia** [comment]
#91

**Comment by inas-fawzi** [comment]
Tasks #91 , #99

**Comment by suha-ab** [comment]
solved
