### ISSUE TITLE
(User Story) - Student/Candidate User - Create a profile

### ISSUE THREAD

**Issue by inas-fawzi** [LachezaraLaz/341-soen341project2023#7]
As a student/candidate user, I would like to create a profile that employer users can view, so that I can showcase my abilities and increase my chances of being selected for a job by an employer.

**Comment by suha-ab** [comment]
Story Points: 8

**Comment by inas-fawzi** [comment]
Related Tasks #63 #64

**Comment by LachezaraLaz** [comment]
any user can create a profile successfully
