### ISSUE TITLE
(User Story) - Student/Candidate User - Create an account/register

### ISSUE THREAD

**Issue by inas-fawzi** [LachezaraLaz/341-soen341project2023#8]
As a student/candidate user, I would like to be able to create and register my own personal account, so that I have an identity within the application and continued access to this identity.

**Comment by suha-ab** [comment]
Story Points: 4

**Comment by LachezaraLaz** [comment]
#44

**Comment by suha-ab** [comment]
#53

**Comment by inas-fawzi** [comment]
Related Tasks #61 #62

**Comment by suha-ab** [comment]
#68
