### ISSUE TITLE
JobDescription.Html

### ISSUE THREAD

**Issue by SahanaCoding** [LachezaraLaz/341-soen341project2023#82]
`<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="../static/css/jobDashboardCSS.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://kit.fontawesome.com/e4ad6adbad.js" crossorigin="anonymous"></script>

  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  
  <style>
    .custom {
      width: 40%;
    }
  </style>

</head>

<body>

  <div class="container-fluid">
    <div class="row">
      <ul class="nav-bar">
        <li><a class="name" href="../Login/Login-html%20file.html"><b><i>I</i>mplico</b></a></li>
        <li><a href="../Profile/profile.html"><i class="fa fa-fw fa-user"></i> Me</a></li>
        <li><a href="#"><i class="fa fa-fw fa-envelope"></i> Jobs</a></li>
        <li><a class="active" href="../Login/Login-html%20file.html" href="#"><i class="fa fa-fw fa-home"></i> Home</a>
        </li>
      </ul>
    </div>
    <br><br><br>

    <div class="row">
        <div class="h-100 d-flex align-items-left justify-content-center">
          <div class="col-8 ps-5 pt-4 pb-4 pe-4 bg-light rounded">
            <div class="row px-3 py-3 text-left">
              
              <div class="position-relative">
                <img src="../static/HelpingPeople.jpg" alt="HappyMan" class="img-fluid float-end" style="width: 40%; border: 2px solid lightblue;">
                <div class="centered" style="align-items:center;width: 60%;">
                    <h4>{{Web Application Developer}}</h4>
                    <h5>{{Matrox}}</h5> <br>
                </div>
            </div>
            
            
          

            
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
            

          
    
              
    <div class="row">
      <div class="h-100 d-flex align-items-left justify-content-left">
        <div class="col-8 ps-2 pt-2 pb-2 pe-3 w-100 bg-light rounded ">
          <div class="row px-2 py-2 text-left ">
          </div>

                <div class="row px-3 py-3 text-left">
                  <div class="d-flex align-items-center">
                    <h6 class="mb-0">{{Full Time}}</h6> 
                    <br><br>
                    <span class="mx-2">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-briefcase" viewBox="0 0 16 16">
                        <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v8A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1h-3zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5zm1.886 6.914L15 7.151V12.5a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5V7.15l6.614 1.764a1.5 1.5 0 0 0 .772 0zM1.5 4h13a.5.5 0 0 1 .5.5v1.616L8.129 7.948a.5.5 0 0 1-.258 0L1 6.116V4.5a.5.5 0 0 1 .5-.5z"/>
                      </svg>
                    </span>
                  </div>
                  
                  <strong> {{Position Summary}}</strong> <br>
                  <p>As a web developer for the IT department, you will develop and maintain custom 
                    web applications used by the various business units of the organization.
                     The right candidate for this role will 
                     be a motivated and energetic developer, 
                     who enjoys finding solutions to a varying number of challenges, 
                     is detail-oriented and thrives on working in a varied, fast paced environment.</p>

                     <strong> {{Responsabilities}}</strong> <br>
                     <p>As a web developer for the IT department, you will develop and maintain custom </p>
                      <br>
                     <strong> {{Qualifications}}</strong> <br>
                     <p>  Possess a Bachelor’s degree in Computer Science or related field.</p>
                      <p> Have at least one year of work experience in web application development, 
                        using C#, ASP.NET, T-SQL, PHP, HTML, CSS and JavaScript.</p>

                </div>

                <button class="btn btn-info text-light" type="Apply">Apply</button>
 
                <button class="btn btn-info text-light" type="Save">Save</button>
          </div>

      <br><br><br>

      

</body>

</html>`

**Comment by SahanaCoding** [comment]
here is what I got for description of job page

**Comment by LachezaraLaz** [comment]
error
