### ISSUE TITLE
(User Story) - Student/Candidate User - login

### ISSUE THREAD

**Issue by inas-fawzi** [LachezaraLaz/341-soen341project2023#9]
As a student/candidate user, I would like to be able to login to my account, such that there is a verification process before I am able to access my identity within the application, ensuring that only I can access this identity.

**Comment by suha-ab** [comment]
Story Points: 6

**Comment by LachezaraLaz** [comment]
#44

**Comment by inas-fawzi** [comment]
Related Tasks #59 #60
